@baseUrl = http://localhost:8080
@json = application/json
@refreshToken = refreshToken

### Health
GET {{baseUrl}}/api/health

### Dev Create User (201 Created)
POST {{baseUrl}}/api/users
Content-Type: {{json}}

{
  "name": "Pierri",
  "email": "pierri@test.com",
  "password": "123456"
}

### Dev Create User (duplicado - deve falhar)
POST {{baseUrl}}/api/users/dev-create
Content-Type: {{json}}

{
  "name": "Pierri 2",
  "email": "pierri@test.com",
  "password": "123456"
}

### Dev Create User (validação - email inválido)
POST {{baseUrl}}/api/users/dev-create
Content-Type: {{json}}

{
  "name": "Teste",
  "email": "email-invalido",
  "password": "123456"
}

### Dev Create User (validação - password curto)
POST {{baseUrl}}/api/users/dev-create
Content-Type: {{json}}

{
  "name": "Teste",
  "email": "teste@teste.com",
  "password": "123"
}

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: {{json}}

{
  "name": "Pierri",
  "email": "pierri2@test.com",
  "password": "123456"
}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: {{json}}

{
  "email": "pierri2@test.com",
  "password": "123456"
}

### Refresh
POST {{baseUrl}}/api/auth/refresh
Content-Type: {{json}}

{
  "refreshToken": "8efc9de9-f933-438f-9cb8-73cd8ddac5f9.22fd90f1-3472-4edf-beab-bded857891dc"
}
 
### Me (protected)
GET {{baseUrl}}/api/me
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJwZXJzb25hbC1maW5hbmNlIiwic3ViIjoiMSIsImVtYWlsIjoicGllcnJpMkB0ZXN0LmNvbSIsImlhdCI6MTc3MDUwMzY4MCwiZXhwIjoxNzcwNTA0NTgwfQ.t_6rKP8qiN-aKZwmq3SlqdGgLuCeLnZ6aW_wiFi1VTwnZbnFijniqmlfiHQGltFC
