@baseUrl = http://localhost:8080
@json = application/json

#############################################
# 0) Health
#############################################

### Health
GET {{baseUrl}}/api/health


#############################################
# 1) Auth
#############################################

### @name login
POST {{baseUrl}}/api/auth/login
Content-Type: {{json}}

{
  "email": "pierri2@test.com",
  "password": "123456"
}


#############################################
# 2) Protected - Me (usa token do login)
#############################################

### Me (protected)
GET {{baseUrl}}/api/me
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJpc3MiOiJwZXJzb25hbC1maW5hbmNlIiwic3ViIjoiMSIsImVtYWlsIjoicGllcnJpMkB0ZXN0LmNvbSIsImlhdCI6MTc3MDU3NjQ2OSwiZXhwIjoxNzcwNTc3MzY5fQ.3o9Vs3i83UoLR5ew6FrN8Y74JKSHiaWwrPjTKRqlYWU5N9XD8lnS8pyP6uoM-SYN


#############################################
# 3) Accounts (protected)
#############################################

### Accounts - List
GET {{baseUrl}}/api/accounts
Authorization: Bearer {{login.response.body.accessToken}}

### Accounts - Create
POST {{baseUrl}}/api/accounts
Content-Type: {{json}}
Authorization: Bearer {{login.response.body.accessToken}}

{
  "name": "Banco Nubank",
  "type": "BANK",
  "initialBalanceCents": 12000
}

### Accounts - Update
PUT {{baseUrl}}/api/accounts/1
Content-Type: {{json}}
Authorization: Bearer {{login.response.body.accessToken}}

{
  "name": "Banco Inter (Atualizado2)",
  "type": "BANK",
  "initialBalanceCents": 250000
}

### Accounts - Delete
DELETE {{baseUrl}}/api/accounts/1
Authorization: Bearer {{login.response.body.accessToken}}
